[package]
name = "renet_netcode"
version = "0.0.1"
edition = "2021"

[features]
bevy = ["dep:bevy_ecs"]

[dependencies]
renet = { version = "0.0.16", path = "../renet" }
renetcode = { path = "../renetcode", version = "0.0.12" }
bevy_ecs = { version = "0.14", optional = true }
log = "0.4.19"

[dev-dependencies]
env_logger = "0.11"